#
# This workflow runs an ensembl of structural variant (SV) callers on a set of
# paired samples (BAM files, tumor vs. normal) provided in a CSV file.
#
# The workflow settings and its deployment are controlled by two config files:
#   config.yaml - set input/output files, SV callers' params, requirements etc.
#   environment.yaml - set software dependencies incl. versions
#

from helper_functions import *

shell.executable("/bin/bash")
configfile: "analysis.yaml"

__author__ = 'Arnold Kuzniar'
__version__ = '0.9.6'
__license__ = 'Apache License, Version 2.0'


localrules: all

rule all:
    input:
        make_output()

# include rules per SV caller
include: "rules/manta.smk"
include: "rules/delly.smk"
include: "rules/lumpy.smk"
include: "rules/gridss.smk"
