#
# This workflow includes several structural variant (SV) detection and
# post-processing tools for detecting somatic or germline SVs in single- or
# paired-sample WGS data, respectively.
#

from helper_functions import *

shell.executable("/bin/bash")


__author__ = 'Arnold Kuzniar'
__version__ = '1.1.3'
__license__ = 'Apache License, Version 2.0'


localrules: all

rule all:
    input:
        make_all()

# include rules
include: "rules/manta.smk"
include: "rules/delly.smk"
include: "rules/lumpy.smk"
include: "rules/gridss.smk"
include: "rules/survivor.smk"
